# PARENT_ITEM_ID에 존재하지 않는 ITEM_ID가 정답
SELECT
    I.ITEM_ID AS ITEM_ID,
    I.ITEM_NAME AS ITEM_NAME,
    I.RARITY AS RARITY
FROM ITEM_INFO I
LEFT OUTER JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
WHERE T.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC;

