-- 코드를 입력하세요
WITH TOTAL_USER AS (
    SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
    
    
SELECT 
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT CNT FROM TOTAL_USER), 1) AS PUCHASED_RATIO
FROM USER_INFO AS U
    JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
WHERE DATE_FORMAT(U.JOINED, "%Y") = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;