-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) AS YEAR, 
       MONTH(O.SALES_DATE) AS MONTH, 
       COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
       ROUND(COUNT(DISTINCT O.USER_ID)/(SELECT COUNT(*) 
                                      FROM USER_INFO 
                                      WHERE JOINED LIKE '2021%'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
WHERE O.USER_ID IN (SELECT USER_ID
                  FROM USER_INFO
                  WHERE JOINED LIKE '2021%')
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH ASC;