-- 코드를 입력하세요
WITH TOTAL_USER AS (
    SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)
    
    
SELECT 
    DATE_FORMAT(O.SALES_DATE, "%Y") AS YEAR, 
    DATE_FORMAT(O.SALES_DATE, "%m") AS MONTH, 
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT CNT FROM TOTAL_USER), 1) AS PUCHASED_RATIO
FROM USER_INFO AS U
    JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;