WITH JULY AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS CNT 
    FROM JULY 
    GROUP BY FLAVOR 
    ORDER BY CNT DESC
), 
FIRST AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS CNT 
    FROM FIRST_HALF 
    GROUP BY FLAVOR 
    ORDER BY CNT DESC
)

SELECT J.FLAVOR AS FLAVOR
FROM JULY AS J
    JOIN FIRST AS F
    ON J.FLAVOR = F.FLAVOR
ORDER BY (J.CNT + F.CNT) DESC
LIMIT 3;

