-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT SUM(TOTAL_ORDER) AS CNT, FLAVOR
    FROM FIRST_HALF
    GROUP BY FLAVOR
    UNION ALL
    SELECT SUM(TOTAL_ORDER) AS CNT, FLAVOR
    FROM JULY
    GROUP BY FLAVOR
) AS TMP
GROUP BY FLAVOR
ORDER BY SUM(CNT) DESC
LIMIT 3;