-- 코드를 입력하세요
WITH RECURSIVE TMP AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TMP WHERE HOUR < 23
)

SELECT
    T.HOUR AS HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM TMP T
LEFT JOIN ANIMAL_OUTS A
    ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY HOUR;