-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, 
        DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATA_OF_BIRTH 
FROM MEMBER_PROFILE 
WHERE GENDER = 'W'
    AND DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') LIKE '%-03-%' 
    AND TLNO IS NOT NULL 
ORDER BY MEMBER_ID ASC;