-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID
WHERE USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
) AND STATUS = 'DONE'
GROUP BY WRITER_ID
ORDER BY TOTAL_SALES ASC;

# SELECT WRITER_ID, SUM(PRICE)
#     FROM USED_GOODS_BOARD
#     WHERE STATUS = 'DONE'
#     GROUP BY WRITER_ID
#     HAVING SUM(PRICE) >= 700000;


