SELECT 
    E.EMP_NO AS EMP_NO,
    E.EMP_NAME AS EMP_NAME,
    CASE
        WHEN SUM(G.SCORE) / 2 >= 96 THEN 'S'
        WHEN SUM(G.SCORE) / 2 >= 90 THEN 'A'
        WHEN SUM(G.SCORE) / 2 >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SUM(G.SCORE) / 2 >= 96 THEN E.SAL * 0.2
        WHEN SUM(G.SCORE) / 2 >= 90 THEN E.SAL * 0.15
        WHEN SUM(G.SCORE) / 2 >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_GRADE G
JOIN HR_EMPLOYEES E
    ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO
ORDER BY EMP_NO;