WITH TMP AS (
    SELECT COUNT(REVIEW_ID) AS CNT, MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1
)

SELECT 
    M.MEMBER_NAME AS MEMBER_NAME,
    R.REVIEW_TEXT AS REVIEW_TEXT, 
    DATE_FORMAT(R.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE M
    JOIN REST_REVIEW R
        ON M.MEMBER_ID = R.MEMBER_ID
    JOIN TMP T
        ON M.MEMBER_ID = T.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;

