-- 코드를 입력하세요
SELECT
    M.MEMBER_NAME AS MEMBER_NAME,
    R.REVIEW_TEXT AS REVIEW_TEXT,
    R.REVIEW_DATE AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID 
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC 
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;