SELECT
    M.YR AS YEAR,
    M.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YR,
        MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON YEAR(E.DIFFERENTIATION_DATE) = M.YR
ORDER BY YEAR, YEAR_DEV;

# 분화된 연도별 가장 큰 대장균의 크기
# SELECT 
#     YEAR(DIFFERENTIATION_DATE),
#     MAX(SIZE_OF_COLONY)
# FROM ECOLI_DATA
# GROUP BY YEAR(DIFFERENTIATION_DATE)