SELECT
    I.ID AS ID,
    N.FISH_NAME AS FISH_NAME,
    I.LENGTH AS LENGTH
FROM FISH_NAME_INFO N
JOIN FISH_INFO I
    ON N.FISH_TYPE = I.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID;

# 물고기 종류별로 가장 큰 물고기 길이
