-- 코드를 입력하세요
WITH TMP AS (
    SELECT
        *,
        RANK() OVER (ORDER BY VIEWS DESC) AS RNK
    FROM USED_GOODS_BOARD
)

SELECT
    CONCAT('/home/grep/src/', T.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT)AS FILE_PATH
FROM TMP T
JOIN USED_GOODS_FILE F
    ON T.BOARD_ID = F.BOARD_ID
WHERE T.RNK = 1
ORDER BY F.FILE_ID DESC;