-- 코드를 입력하세요
WITH RECURSIVE TMP AS (
    SELECT 0 AS PRICE
    UNION ALL
    SELECT PRICE + 10000 FROM TMP WHERE PRICE < 90000
)

# SELECT FLOOR(PRICE/10000) * 10000 FROM PRODUCT

SELECT
    T.PRICE AS PRICE_GROUP,
    COUNT(PRODUCT_ID) AS PRODUCTS
FROM TMP T
JOIN PRODUCT P
    ON T.PRICE = FLOOR(P.PRICE / 10000) * 10000
GROUP BY T.PRICE
ORDER BY PRICE_GROUP;